// Schema modules will be generated by iuliia-codegen
// Run `cargo run -p iuliia-codegen` to populate this directory

use crate::UnknownSchemaError;

/// Transliterate input text using a named schema.
///
/// # Errors
/// Returns `UnknownSchemaError` if the schema name is not recognized.
pub fn transliterate(input: &str, schema_name: &str) -> Result<String, UnknownSchemaError> {
    let _ = input;
    Err(UnknownSchemaError::new(schema_name))
}

/// Returns all available schema names (including aliases).
pub fn schema_names() -> &'static [&'static str] {
    &[]
}
