[package]
name = "iuliia-codegen"
version = "0.1.0"
authors = ["Akhan Zhakiyanov <ahanoff@gmail.com>"]
edition = "2018"

[dependencies]
codegen = "0.1.3"
serde = { version = "1.0.113", features = ["derive"] }
serde_json = "1.0.55"
clap = "2.33.1"
anyhow = "1.0.31"
